apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: citus-data
  namespace: citus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: citus-coordinator
  namespace: citus
  labels:
    app: citus-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citus-coordinator
  template:
    metadata:
      labels:
        app: citus-coordinator
    spec:
      containers:
      - name: citus
        image: citusdata/citus:12.1
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: citus-storage
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: citus-storage
        persistentVolumeClaim:
          claimName: citus-data
